### ISSUE TITLE
How to prevent data loss after page refresh

### ISSUE THREAD

**Issue by mateuszral** [atlassian/react-sweet-state#124]

**Comment by albertogasparin** [comment]
It really depends on your use case. You can build that by using a `Container` and a hook to subscribe to state updates and save them to localStorage.
Then you need a simple `useEffect` that saves the store state on localStorage on data change:

```js
const useHook = createHook(Store);

const LocalStorageSaver = () => {
  const [state] = useHook();
  useEffect(() => {
    localStorage.setItem('state', JSON.stringify(state));
  }, [state]);
  return null
}
```

Then have a look at [the rehydration docs](https://atlassian.github.io/react-sweet-state/#/advanced/rehydration?id=hydrate-through-a-container) as can be easily adapted to populate the state on page load from localStorage.
