### ISSUE TITLE
Is this lib still maintained?

### ISSUE THREAD

**Issue by handrer** [atlassian/react-sweet-state#151]
I have used this lib in the past, but it seems to be abandoned, with many PR.
Is it still maintained and used? or it's better to go for something like https://github.com/pmndrs/zustand

**Comment by albertogasparin** [comment]
Yes it is, used in production in several products. Nearly all the PRs are related to dev dependencies that will never be installed by consumers, so not affecting the library usage. Same for the issues: there is only one open bug (that we have a PR open for) and all other are enhancements or new features (some waiting react 18 release to be developed). 

Generally, the fact that a library is stable and almost bug free does not mean is abandoned :)
