### ISSUE TITLE
[Documentation request] Comparison of bundle sizes

### ISSUE THREAD

**Issue by matthew-dean** [atlassian/react-sweet-state#166]
Can you add in https://atlassian.github.io/react-sweet-state/#/introduction/comparison how this library compares to others in terms of bundle size? And do you know this information off-hand?

For example, the docs say:

> sweet-state was developed to solve some pain points within a 1M+ lines codebase

That sounds like an awful lot, which seems like a drawback of `react-sweet-state`, but it's not actually clear how this compares.

**Comment by albertogasparin** [comment]
If you look at redux standalone, absolutely. But usually you don't use it on its own, you use it via [react-redux](https://bundlephobia.com/package/react-redux@8.0.1) bindings, which means you need to add 14.4KB to those 4.4KB. So the fair-ish comparison is:
- `redux` + `react-redux`: 18.8KB (min)
- `react-sweet-state`: 10.2KB (min)

Making RSS almost 50% more lightweight. I might think of a way to call it out in the comparison, however need to find a way to keep it up to date, as both projects care about performance and bundle size so improvements between versions are to be expected.
