### ISSUE TITLE
better type/name for dispatched actions

### ISSUE THREAD

**Issue by cbejensen** [atlassian/react-sweet-state#181]
Hi, thanks for the great lib! I've been using Redux Devtools to monitor actions, and noticed that when I dispatch an action from another action, the `type` is just the parent action appended with `.dispatch`.

```ts
export const save = () => ({ dispatch }) => {
	dispatch(confirmSave()); // shows up in devtools as `save.dispatch`
};
```

It's not clear in devtools which action was dispatched by `save`.

I get that `dispatch` has no way to know the name of the action, but was wondering if you'd consider allowing `dispatch` to receive an options object as a 2nd argument, which could follow the same pattern as the `Store` by offering a `name` prop.

```ts
export const save = () => ({ dispatch }) => {
	dispatch(confirmSave(), { name: 'Confirm Save' }); // shows up in devtools as `Confirm Save`
};
```

**Comment by albertogasparin** [comment]
That seems like a bit invasive as API, especially because readers might think that such object is passed around (instead it is just for debug purposes).
I'd rather prefer to find a way to have named thunks, so `confirmSave` can be logged without consumers needing to manually name dispatches
