### ISSUE TITLE
Hook mount/unmount time depends at number of hooks on page

### ISSUE THREAD

**Issue by andrewsokolov** [atlassian/react-sweet-state#202]
For big projects, we have ~ 8000 hooks on the page for multiple stores.
For the biggest store, it's around 4000 on the page. 

Mount/unmount each sweet state hook do subscribe/unsubscribe operation on the store.
And implementation of this subscribe/unsubscribe has O(n) complexity, so when need to mount 4000 hooks at once it becomes very painful for UI performance. 

Problematic parts highlighted in the screenshot:
![Screenshot 2023-05-24 at 12 29 35](https://github.com/atlassian/react-sweet-state/assets/336626/be34e93b-a2a9-4ee1-9b68-ae5643c57cef)

Also the video with numbers:

[![Watch the video](https://youtu.be/0g1uo3Nv47k)](https://youtu.be/0g1uo3Nv47k)

And if we replace js array with `Set` time of subscribe/unsubscribe close to 0 ms and has O(1) complexity

![Screenshot 2023-05-24 at 13 05 25](https://github.com/atlassian/react-sweet-state/assets/336626/b507ccbf-3b1d-41d4-afc2-4888c2b9ea17)

**Mount big view:**

Before:
![Screenshot 2023-05-24 at 13 03 59](https://github.com/atlassian/react-sweet-state/assets/336626/da4aa243-61b3-4749-8c7c-9e5f0cda2304)
After:
![Screenshot 2023-05-24 at 12 59 18](https://github.com/atlassian/react-sweet-state/assets/336626/abefd988-a7e4-4321-85d6-5721abcf36de)

**Scroll in virtualized list:**

Before:
![Screenshot 2023-05-24 at 13 04 16](https://github.com/atlassian/react-sweet-state/assets/336626/7415eb84-9c71-47e3-af76-bb8106509dd3)
After:
![Screenshot 2023-05-24 at 12 59 48](https://github.com/atlassian/react-sweet-state/assets/336626/3abfcf5c-95a0-4cec-bf5e-c4e78fba0f99)

**Unmount big view:**

Before:
![Screenshot 2023-05-24 at 13 04 33](https://github.com/atlassian/react-sweet-state/assets/336626/472a3ca1-2ae3-4090-9050-6779c8a897fb)
After:
![Screenshot 2023-05-24 at 13 00 08](https://github.com/atlassian/react-sweet-state/assets/336626/830689ea-426f-4bf4-8772-1a97feddc4e2)

**Comment by albertogasparin** [comment]
Great finding!! Let me know if you struggle finding time to raise a PR in the next few days/week 😉
