### ISSUE TITLE
A store's `onUpdate` handler is not called in React `StrictMode`

### ISSUE THREAD

**Issue by dclark-atlassian** [atlassian/react-sweet-state#225]
# Problem

1. Create a store with an `onUpdate` handler
2. Render it inside of `<React.StrictMode />`
3. Fire some updates to the store
4. The `onUpdate` handler is not called during updates

# Reproduction steps

I created a [codesandbox](https://codesandbox.io/p/sandbox/onupdate-strict-mode-demo-th5v2t) to demo the issue

You can see the `onUpdate` fail to fire here: 
<img src="https://github.com/atlassian/react-sweet-state/assets/149625585/a753d58e-0453-4267-a8e5-4650200fa58b" width="300px" />

**Comment by albertogasparin** [comment]
Fixed in v2.7.2
