### ISSUE TITLE
Store is not removed from the registry in StrictMode

### ISSUE THREAD

**Issue by hinok** [atlassian/react-sweet-state#226]
## Demo

https://codesandbox.io/p/sandbox/oncleanup-issue-not-called-m3ptjs?workspaceId=042b24d6-2010-4590-9678-d2c185d774af

#### When `StrictMode` is disabled

1. Disable `StrictMode`
2. Click a few times `Click {n} times` button.
3. Change project.

**Expected**
The button should display `Click 0 times`.

**Current**
The button displays `Click 0 times`.

#### When `StrictMode` is enabled

1. Enable `StrictMode`
2. Click a few times `Click {n} times` button.
3. Change project.

**Expected**
The button should display `Click 0 times`.

**Current**
The button displays `Click {n} times`.

---

When `Container` is removed from the React tree then `useEffect` is triggered defined in `FunctionContainer`.

There is a check to see if `storeState.listeners().size` is equal to `0` before calling `if (scope) registry.deleteStore(Store, scope);`.

In `StrictMode` the following line

https://github.com/atlassian/react-sweet-state/blob/0384e2803a60a59287b45a2ef3d3e7f6bfccce61/src/components/container.js#L176

is never called because there is always one listener and it's always that listener defined below

 https://github.com/atlassian/react-sweet-state/blob/0384e2803a60a59287b45a2ef3d3e7f6bfccce61/src/components/container.js#L75 so it looks like `unsubscribe()` is not really removing listener

https://github.com/atlassian/react-sweet-state/blob/0384e2803a60a59287b45a2ef3d3e7f6bfccce61/src/components/container.js#L160

**Affected code**

https://github.com/atlassian/react-sweet-state/blob/0384e2803a60a59287b45a2ef3d3e7f6bfccce61/src/components/container.js#L168-L177

**Comment by albertogasparin** [comment]
Fixed in v2.7.2
