### ISSUE TITLE
Feature Idea: `excludeActions` option for `createHook`

### ISSUE THREAD

**Issue by dclark-atlassian** [atlassian/react-sweet-state#229]
# Feature Idea

I wanted to solicit feedback on a feature idea, and I was wondering if it's already been discussed.

Sometimes you may want a hook that provides read-only access to a value in the store. Mostly for simplicity, but also because you may want to draw clear line around what external consumers can update in the store.

This is easy enough to do by wrapping the hooks created by RSS in a custom hook that you export, but I was wondering what you thought about adding an `excludeActions` option for the `createHook` helper.

It could default to false for backwards compatibility.

# Usage example

```ts
export const useName = createHook(Store, {
	selector: (state: { name }) => name,
	excludeActions: true,
});

// ... then somewhere in your app:

const name = useName()
```

This way we know that any consumers importing useName can only read the value.

**Comment by dclark-atlassian** [comment]
Sorry, I accidentally opened this before I was done writing it. Re-opening now.

**Comment by anacierdem** [comment]
`createStateHook` might be what you’re looking for.

**Comment by dclark-atlassian** [comment]
@anacierdem yep, you are so right!

**Comment by dclark-atlassian** [comment]
closing b/c createStateHook solves my use case. Thanks @anacierdem
