### ISSUE TITLE
Cross-store selectors and computed state

### ISSUE THREAD

**Issue by cytrowski** [atlassian/react-sweet-state#31]
If I decide to normalize the state and decompose my state management logic into multiple files will I be able to get the computed state efficiently without writing dirty hacks to query state from multiple stores using reselect?

**Comment by albertogasparin** [comment]
Can you provide an example?

**Comment by cytrowski** [comment]
We have one store which manages users:
```
{
  order: [1, 2, 3]
  entities: {
    "1": { id: 1, name: 'John' ....},
    ....
  }
}
```
And another managing articles:
```
{
  order: [1, 2, 3]
  entities: {
    "1": { id: 1, title: 'Hello World', authorId: 1},
    ....
  }
}
```
I want to query both to display user details next to an article. Where should I put the selector? The way I see it now is creating one selector in users store which gets user by `id` and another in `articles` and then use two hooks inside my component to get proper data. Then merge those in the component.

My point here is that I'm missing a way of defining selectors outside the component tree. However preparing a custom hook for that looks like a reasonable thing to do, eg. `useArticleWithAuthor`

**Comment by albertogasparin** [comment]
Yes, `useArticleWithAuthor` is the suggested way. The same thing you would do when dealing with multiple `useState` hooks. Sweet-state hooks and subscribers accept custom props/args as an input, so you can use the selectors like:

```js
const useArticleWithAuthor = (articleId) => {
  const [article] = useArticleById(articleId);
  const [author] = useUserById(article.authorId);
  return { article, author };
}
```
