### ISSUE TITLE
Redux devtools not working with the examples

### ISSUE THREAD

**Issue by cytrowski** [atlassian/react-sweet-state#33]
https://atlassian.github.io/react-sweet-state/#/advanced/devtools

The docs are saying that devtools are enabled by default. I checked it and this flag is initially set to `false`. I switched it to `true` but it does not make devtools detect the app.

**Comment by albertogasparin** [comment]
Oh right, `devtools` are `false` by default: should update the docs, thanks. 
If you load the examples in the repo, `advanced-flow` and `advanced-coped-flow` have the `devtools` turned on and you can see and interact with the stores (just checked). 
If it is not working for you do you mind sharing the snippet you wrote?

**Comment by cytrowski** [comment]
Thank you - it works for me now :)
