### ISSUE TITLE
Displaying store name in redux dev tools

### ISSUE THREAD

**Issue by cytrowski** [atlassian/react-sweet-state#35]
Is there a way of displaying the store name next to an action in redux dev tools. I can imagine prefixing the action type of having an extra `meta` attribute there to see which store actually handled the action.

**Comment by albertogasparin** [comment]
Stores can have custom names, you just have to provide a `name` attribute on creation (https://atlassian.github.io/react-sweet-state/#/api/store). That way in the devtools stores dropdown you can differentiate between them.
Is that what you are after?

**Comment by cytrowski** [comment]
Yep, I've just figured that out and wanted to close this issue ;)
