### ISSUE TITLE
How can I trigger an action from a life cycle in a class component?

### ISSUE THREAD

**Issue by impactcolor** [atlassian/react-sweet-state#62]
In example 
```
ComponentDidMount() {
  // Trigger action in my sweet state store
}
```
The examples show using it with use effect, however with class components I can't use hooks or I get an error.

**Comment by albertogasparin** [comment]
There are 3 ways of doing it. The suggested one is wrap your component and pass props down:

```js
const Wrapper = () => {
  const [state, actions] = useCounter();
  return <MyComponent counterState={state} counterActions={actions} />
}
```
This is a natural way of solving the problem but requires you to create an additional wrapper.

Another way is to create a dedicated component that fires the onMount action for you:

```js
const TriggerOnMount = ({ action, args = [] }) => {
  useEffect(() => { action(...args); }, [])
  return null;
}

class MyComponent extends Component {
  render() {
    return (
      <CounterSubscriber>
        {(state, actions) => <TriggerOnMount action={actions.increment} args={[1]}} />}
      </CounterSubscriber>
    )
  }
}
```
This way you keep a flat tree, you can abstract away `useEffect` and you can still pass `MyComponent` state and props to the action. This is the most flexible solution.

Last option is the most hacky:

```js
class MyComponent extends Component {
  componentDidMount() {
    this.counterActions.increment(1);
  }
  render() {
    return (
      <CounterSubscriber>
        {(state, actions) => {
          this.counterActions = actions;
          return null;
        }
      </CounterSubscriber>
    )
  }
}
```
It is the most concise, but you are setting a class variable from its rendered children, which is a bit unnatural, so use it with caution.

**Comment by impactcolor** [comment]
Awesome, thank you!!!
