### ISSUE TITLE
[Question] Relational references akin to references in relational databases

### ISSUE THREAD

**Issue by ArturJS** [atlassian/react-sweet-state#65]
@albertogasparin Thanks a lot for the great ReactJS library!
I'm curious, is it possible to construct and connect several stores like they have relations akin to references in relational databases?
Thanks!

**Comment by albertogasparin** [comment]
We suggest to do that outside react-sweet-state, using hooks as controllers to connect multiple stores (even multiple sources of data) and handle the coordination between them. 
See https://atlassian.github.io/react-sweet-state/#/recipes/composition and also an answer I gave on a similar topic https://github.com/atlassian/react-sweet-state/issues/59#issuecomment-584469791

**Comment by ArturJS** [comment]
@albertogasparin Many thanks for the details!
Closing as a resolved.
