### ISSUE TITLE
`createStore` type definition should only allow object state

### ISSUE THREAD

**Issue by fizwidget** [atlassian/react-sweet-state#70]
The current TypeScript definitions seem to allow me to create a store with a non-object state type, for example:
```js
type State = string | undefined;
const initialState = undefined;

// ...define actions, etc...

const Store = createStore<State, Actions>({
  initialState,
  actions
});
```

This behaves weirdly at runtime when actions attempt to update the state (e.g. I end up with state as `{0: "1"}` state if I attempt to set the state to "1").

It is mentioned in the docs that the state has to be an object, but ideally the type definitions would enforce this as well.

May also apply to the Flow types - haven't checked them.

**Comment by albertogasparin** [comment]
Yes, types should probably enforce `initialState` to be an object. Would you like to create a PR to fix that?
