### ISSUE TITLE
[question]: How to handle dependent state updates?

### ISSUE THREAD

**Issue by mrceperka** [atlassian/react-sweet-state#72]
Hello,

is there any change, how to solve dependent state updates? Without passing newState as arg to particular hook?

Consider this example please:

```js
export const useFetchDimensionsFromIndexFn = () => {
  const [availableTypes] = useDimensionTypes()
  // ...ton of other deps...
  return () => {
    // do some fetches based on `availableTypes`
  }
}
```

```js
export const useUserInfoFn = () => {
  const userActions = useUserActions()[1]
  const dimensionActions = useDimensionActions()[1]
  const fetchDimensionItemsFromIndex = useFetchDimensionsFromIndexFn()

  const fn = async () => {
    try {
      const next = await userActions.fetchUserInfo()
      
      // How do I wait here? for new dimensionTypes - result of dimensionActions.setTypes
      dimensionActions.setTypes(next.dimensions.map((d) => d.type))
      // Depends on dimension.types
      // I don't want to pass it to `fetchDimensionItemsFromIndex` as arg
      // This will run with stale state!
      await fetchDimensionItemsFromIndex(0, 'union')
    } catch (e) {}
  }

  return fn
}
```

Workaround solution:
```js
export const useUserInfoFn = () => {
  const userActions = useUserActions()[1]
  const dimensionActions = useDimensionActions()[1]
  const fetchDimensionItemsFromIndex = useFetchDimensionsFromIndexFn()
  const [shouldFetch, fetchItems] = React.useState(false)

  React.useEffect(() => {
    const fn = async () => {
      if (shouldFetch) {
        await fetchDimensionItemsFromIndex(0, 'union')
        fetchItems(false)
      }
    }
    fn()
  }, [shouldFetch])

  const fn = async () => {
    try {
      const next = await userActions.fetchUserInfo()
      dimensionActions.setTypes(next.dimensions.map((d) => d.type))

      fetchItems(true)
    } catch (e) {}
  }

  return fn
}
```

I do not like workaround solution at all. Could someone recommend me an architectural change or best practices please? :pray: 

Note: I am migrating redux-logic to react-sweet-state, and some "logics" are performing `getState()`, which will get them fresh state (even if it was updated during execution of that "logic").

Many thanks!

**Comment by albertogasparin** [comment]
The way we suggest people to think about such problem is that you should not rely on the return of the actions themselves. You should let react re-render and consume the state from the hooks again, and trigger side effects as result.
Basically the waterfall happens as a series of re-renders and the logic is driven by dependency changes.

```js
export const useUserInfoFn = () => {
  const [userState, userActions] = useUserActions()
  const [dimensionState, dimensionActions] = useDimensionActions()
  const fetchDimensionItemsFromIndex = useFetchDimensionsFromIndexFn()
  
  useEffect(() => {
    dimensionActions.setTypes(userState.dimentions.map((d) => d.type));
    fetchDimensionItemsFromIndex(0, 'union');
  }, [userState.dimentions, dimensionActions.setTypes]);

  return userActions.fetchUserInfo
}
```

The power of such pattern is that your state is reactive no matter who triggered the state change: if the dependency value changes then useEffect is triggered. Could be a double edge sword if you forget when the effect is triggered and requires a bit of mindset change, but ensures state consistency.

**Comment by mrceperka** [comment]
Thanks for clarification :pray: 

I am afraid that `fetchDimensionItemsFromIndex` will still see the "old" state (previous dimensions) and it will have to run twice to get in sync, which is bad (for me) and I'd have to implement some logic to handle it.

I've tried to implement the same logic in `mobx-state-tree` and found it much easier (I'm still using react-sweet-state but not for complex logic)

Thanks again for the answer, I am closing this issue.
