### ISSUE TITLE
Single/scope containers don't auto remove store when unmounted

### ISSUE THREAD

**Issue by nghiaphunguyen** [atlassian/react-sweet-state#74]
I checked that `react-sweet-state` will remove the store when unmounted in case it hasn't had any subscriber.  But it didn't work in my case. I debugged and found that the deleting happens before subscribers unsubscribed. Did i wrong somewhere or is this the bug?

**Comment by albertogasparin** [comment]
I've verified and that is the case indeed. It is properly cleaned up on scope update however on unmount the check is done on `componentWillUnmount` while the listener removal is done after unmount (due to how `useEffect` works), as you discovered.

**Comment by albertogasparin** [comment]
Will be fixed by https://github.com/atlassian/react-sweet-state/pull/75

**Comment by nghiaphunguyen** [comment]
thanks @alberto

**Comment by albertogasparin** [comment]
Fixed under `react-sweet-state@2.1.0`

**Comment by nghiaphunguyen** [comment]
@albertogasparin thanks alot. upgraded and it works well.
