### ISSUE TITLE
Question: Middleware with typescript.

### ISSUE THREAD

**Issue by ngamolsky** [atlassian/react-sweet-state#79]
Hello! Not sure this is the right place for these kinds of questions but was unsure where to get this information. It says in your documentation that adding middleware uses the same syntax as Redux middleware. These seems to mostly work with strict typing when using typescript, but I want to make sure I am understanding the types correctly.

In your example you have:
```
const logger = storeState => next => fn => {}
```
As the signature for the middleware. I believe that `storeState` is basically just the `Store` object we create, the default `next` function is the default mutator that processes the partial state, but I am confused as to what the `fn` parameter is. When I log it out it seems to be the new partial state after the transformation, is that correct? How are we meant to type these middlewares? when I use the react `Middleware` type, I don't get access to the correct fields in my store state, as there is no way to parameterize the type. Am I supposed to import redux types for this?

Any help would be greatly appreciated. Thanks!

**Comment by ngamolsky** [comment]
Seems to me that the typing for the middlewares defined in your `index.t.ts` file is incorrect `(fn: () => any)`. The final function argument is always the partial state object, and not a function as in redux. Also the mutator function doesn't return anything so the "Changed: " log in the middleware example is always empty.

**Comment by hungpham** [comment]
Hi @ngamolsky, 
There is misleading in the documentation. You can try with the code:
```
import { StoreState } from 'react-sweet-state';

const logger = (storeState: StoreState<any>) => (next: any) => (fn: any) => {
  console.groupCollapsed('Store', storeState.key);
  console.log('prev state:', JSON.parse(JSON.stringify(storeState.getState())));
  console.log('payload:', fn);
  const result = next(fn);
  console.log('next state:', JSON.parse(JSON.stringify(storeState.getState())));
  console.groupEnd();
  return result;
};
```
Hope this help!

**Comment by albertogasparin** [comment]
Thanks for noticing. The docs and the types are misleading/wrong as the third parameter `fn` is in reality the argument you pass to `setState`, so it should be probably named `arg`.
The code @hungpham posted is correct, and there is also a [working example in the examples folder](https://github.com/atlassian/react-sweet-state/blob/master/examples/advanced-flow/index.js#L14).
Docs and types need fixing

**Comment by ngamolsky** [comment]
Thanks for the reply!

**Comment by albertogasparin** [comment]
Docs updated in #80
